### ISSUE TITLE
Limited browsing

### ISSUE THREAD

**Issue by zachconstan** [zebradog/kiosk#81] opened 2016-01-13 14:33 UTC
Kiosk + chromebox are just about exactly what I need for a lobby touchscreen, but I'd like to limit browsing to a few whitelisted sites. I added an extension to do that in chrome, but Kiosk is not affected by that and can still browse away. Could you add the option to whitelist specific domains?

**Comment by matt-cook** [comment] 2016-02-05 15:57
this is a duplicate of #16. I'll post additional details there.

**Closed by matt-cook** 2016-02-05 15:57 UTC
Labels: duplicate, enhancement
